### ISSUE TITLE
The question about the age value for portable PDB

### ISSUE THREAD

**Issue by ww898** [dotnet/symstore#53]
https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PE-COFF.md
> Version Major=any, Minor=0x504d of the data format has the same structure as above. The Age shall be 1. The format of the .pdb file that this PE/COFF file was built with is Portable PDB. The Major version specified in the entry indicates the version of the Portable PDB format. Together 16B of the Guid concatenated with 4B of the TimeDateStamp field of the entry form a PDB ID that should be used to match the PE/COFF image with the associated PDB (instead of Guid and Age). Matching PDB ID is stored in the #Pdb stream of the .pdb file.

**The Age shall be 1**

You add the `ffffffff` as the age for protable pdb. Why ???

**Comment by tmat** [comment]
Since the age for Portable PDBs is irrelevant (always 1 in the PE debug directory) the Portable PDB key used in [SSQP](https://github.com/dotnet/symstore/blob/master/docs/specs/SSQP_Key_Conventions.md#portable-pdb-signature) doesn't need to include it. Instead we use 'ffffffff' suffix to enable indexing both Portable and Windows PDBs with the same name and GUID on the server. In that case the Windows PDB could be a PDB converted from the Portable PDB and uploaded to the symbol server to support tools that do not understand Portable PDBs.
